// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/thread-polished/ThreadPolished.tsx": () => import("../components/mockups/thread-polished/ThreadPolished.tsx")
};
